---
- name: Install Docker
  hosts: all # aws_ec2 # all # docker_server
  become: yes
  # become_user: root
  tasks:
    - name: Make sur Docker is installed
      yum:  
        name: docker
        update_cache: yes
        state: present
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

- name: Install Docker-compose
  hosts: all # aws_ec2 # all
  become: yes
  vars_files:
    project-vars
  become_user: "{{linux_name}}"
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{remote_arch.stdout}}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x


